---
title: "Kenji T. Hayashi - *Curriculum Vitae*"
format: 
  html: 
    theme:
      - lumen
      - custom.scss
execute: 
  echo: false
  output: asis
---

```{r setup}
library(qcvutils)
library(yaml)

d <- read_yaml("data.yaml")
```

```{r footer}
# Update data in footer by modifying custom.scss
f <- "custom.scss"
s <- readLines(f)
dl <- intersect(grep("date-here", s), grep("content:*", s))
s[dl] <- gsub("(?<=content: )([^;]+)", 
              paste0('"', format(Sys.Date(), "%m/%d/%Y"), '"'), 
              s[dl], 
              perl = TRUE)
writeLines(s, f)
```

:::{style="text-align:center;"}
Ph.D Candidate    
Department of Ecology and Evolutionary Biology    
University of California, Los Angeles   
Email: [kthayashi@ucla.edu](mailto:kthayashi@ucla.edu) | Web: [link here]()
:::

## EDUCATION

```{r education}
education <- d$education
qcv_insert(education)
```

## FUNDING

### Grants

```{r grants}
grants <- d$grants
qcv_insert(grants)
```

### Fellowships & Scholarships

```{r fellowships}
fellowships <- d$fellowships
qcv_insert(fellowships)
```

## HONORS & AWARDS

```{r honors}
honors <- d$honors
qcv_insert(honors)
```

::::::{.group}
## PUBLICATIONS

### Journal Articles

:::{.small}
\* indicates equal contribution
:::
::::::

```{r articles}
articles <- d$publications$articles
qcv_insert_pubs(articles)
```
